# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jy-XfGQrkJkGr8zLRrdEI-rgff6aq54T
"""

marks = [78, 91, 65, 43, 88]

total = sum(marks)
percentage = total/(len(marks)*100) *100

print("Total Marks: ", total)
print("Percentage: ", percentage)

passed = True

for mark in marks:

  if mark < 35:
    passed = False

  if mark > 90:
    print(mark, "- A+")
  elif mark > 80:
    print(mark, "- A")
  elif mark > 70:
    print(mark, "- B+")
  elif mark > 60:
    print(mark,"- B")
  elif mark > 40:
    print(mark, "- C")
  elif mark > 35:
    print(mark, "- D")
  else:
    print(mark, "- Fail")


if passed:
  print("Status : Passed")
else:
  print("Status : Failed")