# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUabubDa06lBl3hvXtqgmQfpnKP3FnK_
"""

num = int(input("Enter a number: "))

if num >= 0:
  if num == 0:
    print("Number is zero")
  else:
    print("Number is positive")
else:
  print("Number is negative")