# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAsuUVdQRqUlGGurn1AIVgAa-5ndRzY5
"""

num = int(input("Enter a num: "))

for i in range(1, 11):
  print(num, "x", i, "=", num*i)