# -*- coding: utf-8 -*-
"""Q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1Lx1KTo-JPTtW7z7S0hhMxxgKcOOreO
"""

num = int(input("Enter a num: "))
numm = num
sum = 0
while num > 0:
  digit = num % 10
  sum += digit
  num = num // 10

print(f"Sum of digits {num}: ", sum)