# -*- coding: utf-8 -*-
"""Q7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGnWey_JgE8Mbj4z3EXaDarA-SXiIQyW
"""

m = [1, 2, 3, 4, 5, 6, 7, 8]

l = [x for x in m if x % 2 ==0 ]
print("List Comprehension")
print(l,"\n")

drivers = ["Kimi", "George", "Lewis", "Max", "Lando"]

d = {driver : i + 1 for i, driver in enumerate(drivers)}
print("Dictionary Comprehension")
print(d,"\n")

s = {x**2 for x in range(1, 21) if x % 2 == 0}
print("Set Comprehension")
print(s)