# -*- coding: utf-8 -*-
"""Q9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyOLUNFZEqHvQSAHrcKILWpXnMZIyqfl
"""

drivers = ["Kimi", "George", "Lewis", "Lando", "Carlos"] #iterables

driver = iter(drivers) #iterator

print("The potential world champion 2026 are :")
print(next(driver), "and", next(driver))

print(next(driver), "and", next(driver), "are fighting for the 3rd place.")

print(next(driver), "is having difficult driving a overweight tractor of a F1 car.")