# -*- coding: utf-8 -*-
"""Q10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWckOnzS-3OALBSy-o13YvDWK-hU-VZS
"""

def seat_generator():
    for row in ["A", "B", "C", "D"]:
        for seat in range(1, 5):
            yield f"Row {row} - Seat {seat}"


for seat in seat_generator():
    print(seat)