# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Rsamhi9G4r09HhHzFbk_bASwPl9b0cz
"""

marks = [87, 56, 00, 34, 62]

for mark in marks:
  if mark == 00:
    continue
  if mark >= 35:
    pass
  if mark < 35:
    print("Subject marks less than 35, FAIL")
    break

  print("Marks : ", mark)