# -*- coding: utf-8 -*-
"""Q6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_E4i-L69_A0CPFuWhK2mdVVihoWoRzbh
"""

Drivers = ["Kimi Antonelli", "George Russel", "Lewis Hamilton", "Lando Norris", "Charles Leclerc"]

for i in range(len(Drivers)):
  print("Championship Position", i+1, ":", Drivers[i])

Teams = {"Mercedez": "Kimi and George", "Ferrari": "Charles and Lewis", "McLaren": "Lando and Piastri"}

print("Teams and Drivers")

for key, value in Teams.items():
  print(key, ":", value)