# -*- coding: utf-8 -*-
"""Q8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tF7W_2Qk8U8VMd2hQptrYhM0WzCzOQwq
"""

fastest_lap = 95.40

def race(team, starting_points):
    team_points = starting_points

    def process_driver(driver, lap_time, points):
        nonlocal team_points
        global fastest_lap

        bonus = 0

        if lap_time < fastest_lap:
            fastest_lap = lap_time
            bonus = 1

        team_points += points + bonus

        print(f"{driver} scored {points + bonus} points")

    process_driver("Kimi Antonelli", 96.10, 18)
    process_driver("George Russell", 95.20, 25)

    print("Team points:", team_points)


race("Mercedes", 100)

print("Overall fastest lap:", fastest_lap)